# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from decimal import Decimal
import core.fields
import dirtyfields.dirtyfields
import django.utils.timezone
import djmoney.models.fields
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(editable=False, db_index=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', django_extensions.db.fields.AutoSlugField(populate_from=b'name', editable=False, blank=True)),
                ('item_type', models.CharField(default=b'category', max_length=10, choices=[(b'category', b'Category'), (b'program', b'Program'), (b'custom', b'Custom')])),
                ('jan_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jan_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('feb_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('feb_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('mar_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('mar_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('apr_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('apr_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('may_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('may_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jun_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jun_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jul_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jul_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('aug_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('aug_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('sep_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('sep_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('oct_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('oct_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('nov_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('nov_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('dec_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('dec_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jan_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jan_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('feb_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('feb_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('mar_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('mar_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('apr_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('apr_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('may_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('may_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jun_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jun_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jul_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jul_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('aug_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('aug_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('sep_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('sep_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('oct_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('oct_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('nov_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('nov_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('dec_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('dec_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jan_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jan_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('feb_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('feb_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('mar_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('mar_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('apr_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('apr_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('may_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('may_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jun_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jun_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jul_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jul_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('aug_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('aug_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('sep_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('sep_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('oct_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('oct_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('nov_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('nov_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('dec_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('dec_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q1_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q1_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q1_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q1_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q1_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q1_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q2_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q2_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q2_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q2_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q2_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q2_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q3_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q3_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q3_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q3_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q3_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q3_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q4_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q4_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q4_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q4_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q4_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q4_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('fiscal_year_actual_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('fiscal_year_actual', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('fiscal_year_plan_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('fiscal_year_plan', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('fiscal_year_variance_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('fiscal_year_variance', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('lft', models.PositiveIntegerField(editable=False, db_index=True)),
                ('rght', models.PositiveIntegerField(editable=False, db_index=True)),
                ('tree_id', models.PositiveIntegerField(editable=False, db_index=True)),
                ('level', models.PositiveIntegerField(editable=False, db_index=True)),
            ],
            options={
                'ordering': ('order',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
