# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import core.models
import dirtyfields.dirtyfields
import djmoney.models.fields
import django_extensions.db.fields
from decimal import Decimal
import core.fields
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0001_initial'),
        ('companies', '0002_auto_20150908_2126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=150)),
                ('slug', django_extensions.db.fields.AutoSlugField(populate_from=b'name', editable=False, blank=True)),
                ('source', models.IntegerField(default=1, verbose_name='Source', choices=[(1, 'Manual'), (2, 'Sales Force')])),
                ('jan_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jan_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jan_contacts', models.IntegerField(default=0)),
                ('jan_mql', models.IntegerField(default=0)),
                ('jan_sql', models.IntegerField(default=0)),
                ('jan_sales', models.IntegerField(default=0)),
                ('jan_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jan_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jan_touches', models.IntegerField(default=0)),
                ('jan_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jan_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jan_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jan_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jan_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jan_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jan_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('jan_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('feb_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('feb_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('feb_contacts', models.IntegerField(default=0)),
                ('feb_mql', models.IntegerField(default=0)),
                ('feb_sql', models.IntegerField(default=0)),
                ('feb_sales', models.IntegerField(default=0)),
                ('feb_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('feb_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('feb_touches', models.IntegerField(default=0)),
                ('feb_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('feb_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('feb_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('feb_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('feb_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('feb_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('feb_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('feb_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('mar_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('mar_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('mar_contacts', models.IntegerField(default=0)),
                ('mar_mql', models.IntegerField(default=0)),
                ('mar_sql', models.IntegerField(default=0)),
                ('mar_sales', models.IntegerField(default=0)),
                ('mar_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('mar_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('mar_touches', models.IntegerField(default=0)),
                ('mar_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('mar_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('mar_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('mar_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('mar_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('mar_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('mar_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('mar_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('apr_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('apr_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('apr_contacts', models.IntegerField(default=0)),
                ('apr_mql', models.IntegerField(default=0)),
                ('apr_sql', models.IntegerField(default=0)),
                ('apr_sales', models.IntegerField(default=0)),
                ('apr_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('apr_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('apr_touches', models.IntegerField(default=0)),
                ('apr_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('apr_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('apr_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('apr_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('apr_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('apr_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('apr_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('apr_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('may_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('may_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('may_contacts', models.IntegerField(default=0)),
                ('may_mql', models.IntegerField(default=0)),
                ('may_sql', models.IntegerField(default=0)),
                ('may_sales', models.IntegerField(default=0)),
                ('may_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('may_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('may_touches', models.IntegerField(default=0)),
                ('may_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('may_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('may_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('may_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('may_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('may_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('may_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('may_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('jun_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jun_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jun_contacts', models.IntegerField(default=0)),
                ('jun_mql', models.IntegerField(default=0)),
                ('jun_sql', models.IntegerField(default=0)),
                ('jun_sales', models.IntegerField(default=0)),
                ('jun_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jun_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jun_touches', models.IntegerField(default=0)),
                ('jun_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jun_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jun_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jun_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jun_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jun_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jun_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('jun_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('jul_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jul_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jul_contacts', models.IntegerField(default=0)),
                ('jul_mql', models.IntegerField(default=0)),
                ('jul_sql', models.IntegerField(default=0)),
                ('jul_sales', models.IntegerField(default=0)),
                ('jul_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jul_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jul_touches', models.IntegerField(default=0)),
                ('jul_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jul_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jul_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jul_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jul_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('jul_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('jul_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('jul_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('aug_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('aug_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('aug_contacts', models.IntegerField(default=0)),
                ('aug_mql', models.IntegerField(default=0)),
                ('aug_sql', models.IntegerField(default=0)),
                ('aug_sales', models.IntegerField(default=0)),
                ('aug_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('aug_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('aug_touches', models.IntegerField(default=0)),
                ('aug_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('aug_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('aug_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('aug_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('aug_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('aug_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('aug_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('aug_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('sep_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('sep_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('sep_contacts', models.IntegerField(default=0)),
                ('sep_mql', models.IntegerField(default=0)),
                ('sep_sql', models.IntegerField(default=0)),
                ('sep_sales', models.IntegerField(default=0)),
                ('sep_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('sep_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('sep_touches', models.IntegerField(default=0)),
                ('sep_touches_per_contact', models.DecimalField(default=0, max_digits=10, decimal_places=1)),
                ('sep_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('sep_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('sep_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('sep_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('sep_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('sep_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('sep_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('sep_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('oct_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('oct_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('oct_contacts', models.IntegerField(default=0)),
                ('oct_mql', models.IntegerField(default=0)),
                ('oct_sql', models.IntegerField(default=0)),
                ('oct_sales', models.IntegerField(default=0)),
                ('oct_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('oct_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('oct_touches', models.IntegerField(default=0)),
                ('oct_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('oct_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('oct_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('oct_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('oct_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('oct_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('oct_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('oct_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('nov_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('nov_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('nov_contacts', models.IntegerField(default=0)),
                ('nov_mql', models.IntegerField(default=0)),
                ('nov_sql', models.IntegerField(default=0)),
                ('nov_sales', models.IntegerField(default=0)),
                ('nov_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('nov_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('nov_touches', models.IntegerField(default=0)),
                ('nov_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('nov_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('nov_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('nov_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('nov_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('nov_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('nov_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('nov_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('dec_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('dec_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('dec_contacts', models.IntegerField(default=0)),
                ('dec_mql', models.IntegerField(default=0)),
                ('dec_sql', models.IntegerField(default=0)),
                ('dec_sales', models.IntegerField(default=0)),
                ('dec_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('dec_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('dec_touches', models.IntegerField(default=0)),
                ('dec_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('dec_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('dec_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('dec_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('dec_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('dec_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('dec_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('dec_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('q1_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q1_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q1_contacts', models.IntegerField(default=0)),
                ('q1_mql', models.IntegerField(default=0)),
                ('q1_sql', models.IntegerField(default=0)),
                ('q1_sales', models.IntegerField(default=0)),
                ('q1_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q1_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q1_touches', models.IntegerField(default=0)),
                ('q1_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q1_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q1_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q1_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q1_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q1_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q1_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('q1_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('q2_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q2_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q2_contacts', models.IntegerField(default=0)),
                ('q2_mql', models.IntegerField(default=0)),
                ('q2_sql', models.IntegerField(default=0)),
                ('q2_sales', models.IntegerField(default=0)),
                ('q2_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q2_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q2_touches', models.IntegerField(default=0)),
                ('q2_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q2_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q2_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q2_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q2_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q2_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q2_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('q2_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('q3_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q3_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q3_contacts', models.IntegerField(default=0)),
                ('q3_mql', models.IntegerField(default=0)),
                ('q3_sql', models.IntegerField(default=0)),
                ('q3_sales', models.IntegerField(default=0)),
                ('q3_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q3_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q3_touches', models.IntegerField(default=0)),
                ('q3_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q3_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q3_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q3_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q3_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q3_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q3_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('q3_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('q4_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q4_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q4_contacts', models.IntegerField(default=0)),
                ('q4_mql', models.IntegerField(default=0)),
                ('q4_sql', models.IntegerField(default=0)),
                ('q4_sales', models.IntegerField(default=0)),
                ('q4_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q4_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q4_touches', models.IntegerField(default=0)),
                ('q4_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q4_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q4_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q4_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q4_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('q4_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('q4_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('q4_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('fiscal_year_cost_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('fiscal_year_cost', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('fiscal_year_contacts', models.IntegerField(default=0)),
                ('fiscal_year_mql', models.IntegerField(default=0)),
                ('fiscal_year_sql', models.IntegerField(default=0)),
                ('fiscal_year_sales', models.IntegerField(default=0)),
                ('fiscal_year_total_sales_value_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('fiscal_year_total_sales_value', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('fiscal_year_touches', models.IntegerField(default=0)),
                ('fiscal_year_cost_per_mql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('fiscal_year_cost_per_mql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('fiscal_year_cost_per_sql_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('fiscal_year_cost_per_sql', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('fiscal_year_average_sale_currency', djmoney.models.fields.CurrencyField(default=b'USD', max_length=3, editable=False, choices=[(b'USD', 'US Dollar')])),
                ('fiscal_year_average_sale', core.fields.DefaultMoneyField(default=Decimal('0'), max_digits=10, decimal_places=0, default_currency=b'USD')),
                ('fiscal_year_touches_to_mql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('fiscal_year_mql_to_sql_conversion', core.fields.PercentField(default=0, max_digits=4, decimal_places=1)),
                ('company', models.ForeignKey(to='companies.Company')),
                ('modified_by', models.ForeignKey(related_name='campaign_last_modified', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True)),
                ('program', models.ForeignKey(to='leads.Program')),
                ('revenue_plan', models.ForeignKey(to='revenues.RevenuePlan')),
                ('segment', models.ForeignKey(to='revenues.Segment')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(core.models.DenormalizedIcmoParentsMixin, dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together=set([('slug', 'program')]),
        ),
    ]
