# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20150922_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='apr_total_sales_value',
            new_name='apr_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='apr_total_sales_value_currency',
            new_name='apr_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='aug_total_sales_value',
            new_name='aug_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='aug_total_sales_value_currency',
            new_name='aug_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='dec_total_sales_value',
            new_name='dec_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='dec_total_sales_value_currency',
            new_name='dec_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='feb_total_sales_value',
            new_name='feb_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='feb_total_sales_value_currency',
            new_name='feb_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='fiscal_year_total_sales_value',
            new_name='fiscal_year_salefs_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='fiscal_year_total_sales_value_currency',
            new_name='fiscal_year_salefs_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='jan_total_sales_value',
            new_name='jan_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='jan_total_sales_value_currency',
            new_name='jan_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='jul_total_sales_value',
            new_name='jul_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='jul_total_sales_value_currency',
            new_name='jul_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='jun_total_sales_value',
            new_name='jun_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='jun_total_sales_value_currency',
            new_name='jun_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='mar_total_sales_value',
            new_name='mar_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='mar_total_sales_value_currency',
            new_name='mar_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='may_total_sales_value',
            new_name='may_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='may_total_sales_value_currency',
            new_name='may_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='nov_total_sales_value',
            new_name='nov_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='nov_total_sales_value_currency',
            new_name='nov_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='oct_total_sales_value',
            new_name='oct_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='oct_total_sales_value_currency',
            new_name='oct_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='q1_total_sales_value',
            new_name='q1_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='q1_total_sales_value_currency',
            new_name='q1_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='q2_total_sales_value',
            new_name='q2_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='q2_total_sales_value_currency',
            new_name='q2_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='q3_total_sales_value',
            new_name='q3_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='q3_total_sales_value_currency',
            new_name='q3_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='q4_total_sales_value',
            new_name='q4_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='q4_total_sales_value_currency',
            new_name='q4_sales_revenue_currency',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='sep_total_sales_value',
            new_name='sep_sales_revenue',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='sep_total_sales_value_currency',
            new_name='sep_sales_revenue_currency',
        ),
    ]
