# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-08 00:06
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0007_auto_20160211_1818'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0007_auto_20160303_1755'),
        ('resources', '0005_auto_20160226_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiantGanttTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('past_due', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('rq_id', models.CharField(max_length=255)),
                ('rq_sort_order', models.SmallIntegerField(blank=True, default=0)),
                ('rq_name', models.CharField(blank=True, max_length=512)),
                ('rq_start_time', models.DateTimeField(blank=True)),
                ('rq_end_time', models.DateTimeField(blank=True)),
                ('rq_effort', models.CharField(blank=True, max_length=255)),
                ('effort_in_seconds', models.IntegerField(blank=True, default=0)),
                ('rq_preferred_start_time', models.DateTimeField(blank=True, null=True)),
                ('rq_indent_level', models.SmallIntegerField(default=0)),
                ('rq_predecessor_indices', models.TextField(blank=True)),
                ('rq_progress_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('rq_resources', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiantgantttask_last_modified', to=settings.AUTH_USER_MODEL)),
                ('revenue_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenues.RevenuePlan')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revenues.Segment')),
            ],
            options={
                'ordering': ('company_id', 'revenue_plan_id', 'rq_sort_order'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
